### ISSUE TITLE
hero past qismidaxam margin ikkita berilgan va katta bo'lib ketgan

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [Andarov/coffee-roaster#6]
![image](https://user-images.githubusercontent.com/99403792/161370774-102fca66-c8c3-4568-81f1-3fe2d8779a51.png)
![image](https://user-images.githubusercontent.com/99403792/161370782-c49a92de-9807-4937-ab90-b589b2a3d8dd.png)

**Comment by Andarov** [comment]
#fixed6
