### ISSUE TITLE
Uncompromising quality degan bo'limdagi margin bottom katta bo'lib ketgan

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [Andarov/coffee-roaster#7]
![image](https://user-images.githubusercontent.com/99403792/161370865-8cdc5bef-bc2e-4e2d-ae42-7f139d9f9460.png)
![image](https://user-images.githubusercontent.com/99403792/161370870-97c968c2-6f91-4de8-a798-b7771079662d.png)

**Comment by Andarov** [comment]
#fixed7
